[package]
name = "leuchtturm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono.workspace = true
sqlx.workspace = true
thiserror.workspace = true
argon2 = { version = "0.4.1", features = ["std"] }
rand_core = { version = "0.6.4", features = ["std"] }
