version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.36
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      # Web UI
      - 16686:16686
      # OTLP
      - 4317:4317
      - 4318:4318
