import { defineConfig } from "oxlint";

const localRules = [
	"consistent-component-hook-groups",
	"namespace-filename-match",
	"no-api-response-schema-in-core",
	"no-direct-fetch",
	"no-effect-try-helper",
	"no-generic-domain-error-class",
	"no-live-suffix",
	"no-local-effect-callback-wrapper",
	"no-local-web-schema",
	"no-namespace-imports",
	"no-non-exact-package-json-versions",
	"no-phosphor-top-level-import",
	"no-relative-imports",
	"no-row-suffix",
	"no-schema-type-alias",
	"no-use-client-server-directives",
	"no-use-params-strict-false",
	"no-variable-alias",
	"no-void-operator",
	"no-vi-mock",
] as const;

export default defineConfig({
	plugins: ["eslint", "typescript", "unicorn", "react", "react-perf", "oxc", "import"],
	options: {
		typeAware: true,
		typeCheck: true,
	},
	jsPlugins: localRules.map((rule) => `./packages/oxlint-plugins/src/${rule}.ts`),
	ignorePatterns: [
		"**/node_modules/**",
		"**/dist/**",
		"**/*.gen.ts",
		"**/sst-env.d.ts",
		".opencode/**",
		".pi/**",
		"packages/oxlint-plugins/**",
		"infra/**",
		"sst.config.ts",
	],
	rules: {
		"consistent-component-hook-groups/consistent-component-hook-groups": "error",
		"namespace-filename-match/namespace-filename-match": "error",
		"no-api-response-schema-in-core/no-api-response-schema-in-core": "error",
		"no-effect-try-helper/no-effect-try-helper": "error",
		"no-generic-domain-error-class/no-generic-domain-error-class": "error",
		"no-live-suffix/no-live-suffix": "error",
		"no-local-effect-callback-wrapper/no-local-effect-callback-wrapper": "error",
		"no-local-web-schema/no-local-web-schema": "error",
		"no-non-exact-package-json-versions/no-non-exact-package-json-versions": "error",
		"no-phosphor-top-level-import/no-phosphor-top-level-import": "error",
		"no-relative-imports/no-relative-imports": "error",
		"no-row-suffix/no-row-suffix": "error",
		"no-schema-type-alias/no-schema-type-alias": "error",
		"no-use-client-server-directives/no-use-client-server-directives": "error",
		"no-use-params-strict-false/no-use-params-strict-false": "error",
		"no-variable-alias/no-variable-alias": "error",
		"no-void-operator/no-void-operator": "error",
		"no-vi-mock/no-vi-mock": "error",
		"@typescript-eslint/no-floating-promises": "off",
		"@typescript-eslint/unbound-method": "off",
		"eslint/no-unused-vars": "off",
		"react/exhaustive-deps": "error",
		"react/rules-of-hooks": "error",
	},
	overrides: [
		{
			files: ["apps/web/**/*.{ts,tsx}"],
			rules: {
				"no-direct-fetch/no-direct-fetch": "error",
			},
		},
		{
			files: ["apps/web/src/components/**/*.{ts,tsx}"],
			rules: {
				"no-namespace-imports/no-namespace-imports": "error",
			},
		},
	],
});
