packages:
  - infra
  - apps/*
  - packages/*

allowBuilds:
  "@rocicorp/zero-sqlite3": true
  core-js: false
  esbuild: false
  msgpackr-extract: false
  msw: false
  protobufjs: false
  tree-sitter-python: set this to true or false

minimumReleaseAge: 720
patchedDependencies:
  drizzle-orm@1.0.0-rc.1: patches/drizzle-orm@1.0.0-rc.1.patch
