/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ApiConfig": {
      "BASE_URL": string
      "POLAR_SERVER": string
      "type": "sst.sst.Linkable"
    }
    "ApiWorker": import("@cloudflare/workers-types").Service
    "Database": import("@cloudflare/workers-types").Hyperdrive
    "Storage": import("@cloudflare/workers-types").R2Bucket
    "Web": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
  }
}

import "sst"
export {}