/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ApiConfig": {
      "BASE_URL": string
      "NODE_ENV": string
      "POLAR_SERVER": string
      "POSTHOG_HOST": {
        "4dabf18193072939515e22adb298388d": string
        "packageVersion": string
        "urn": string
      }
      "type": "sst.sst.Linkable"
    }
    "ApiWorker": {
      "type": "sst.cloudflare.Worker"
    }
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HYPERDRIVE": {
      "type": "sst.sst.Linkable"
    }
    "PlanetScaleDatabaseId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PlanetScaleOrganization": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PolarAccessToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PolarSuccessUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PolarWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostHogHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostHogProjectApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RenderOwnerId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Storage": {
      "name": string
      "type": "sst.cloudflare.Bucket"
    }
    "Web": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "ZeroAdminPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZeroDatabasePassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZeroDatabaseUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}