export const secrets = {
	planetScaleDatabaseId: new sst.Secret("PlanetScaleDatabaseId"),
	planetScaleOrganization: new sst.Secret("PlanetScaleOrganization"),
	postHogHost: new sst.Secret("PostHogHost"),
	postHogProjectApiKey: new sst.Secret("PostHogProjectApiKey"),
	axiomToken: new sst.Secret("AxiomToken"),
	axiomDomain: new sst.Secret("AxiomDomain"),
	axiomLogsDataset: new sst.Secret("AxiomLogsDataset"),
	axiomTracesDataset: new sst.Secret("AxiomTracesDataset"),
	axiomMetricsDataset: new sst.Secret("AxiomMetricsDataset"),
	betterAuthSecret: new sst.Secret("BetterAuthSecret"),
	gitHubClientId: new sst.Secret("GitHubClientId"),
	gitHubClientSecret: new sst.Secret("GitHubClientSecret"),
	polarAccessToken: new sst.Secret("PolarAccessToken"),
	polarSuccessUrl: new sst.Secret("PolarSuccessUrl"),
	polarWebhookSecret: new sst.Secret("PolarWebhookSecret"),
	renderOwnerId: new sst.Secret("RenderOwnerId"),
	zeroAdminPassword: new sst.Secret("ZeroAdminPassword"),
	zeroDatabasePassword: new sst.Secret("ZeroDatabasePassword"),
	zeroDatabaseUsername: new sst.Secret("ZeroDatabaseUsername"),
};

export const apiSecrets = [
	secrets.postHogHost,
	secrets.postHogProjectApiKey,
	secrets.axiomToken,
	secrets.axiomDomain,
	secrets.axiomLogsDataset,
	secrets.axiomTracesDataset,
	secrets.axiomMetricsDataset,
	secrets.betterAuthSecret,
	secrets.gitHubClientId,
	secrets.gitHubClientSecret,
	secrets.polarAccessToken,
	secrets.polarSuccessUrl,
	secrets.polarWebhookSecret,
];
