export const secrets = {
	planetScaleDatabaseId: new sst.Secret("PlanetScaleDatabaseId"),
	planetScaleOrganization: new sst.Secret("PlanetScaleOrganization"),
	betterAuthSecret: new sst.Secret("BetterAuthSecret"),
	gitHubClientId: new sst.Secret("GitHubClientId"),
	gitHubClientSecret: new sst.Secret("GitHubClientSecret"),
	gmailOauthClientId: new sst.Secret("GmailOauthClientId"),
	gmailOauthClientSecret: new sst.Secret("GmailOauthClientSecret"),
	gmailOauthRedirectUri: new sst.Secret("GmailOauthRedirectUri"),
	gmailPubSubTopic: new sst.Secret("GmailPubSubTopic"),
	mailKek: new sst.Secret("MailKek"),
	polarAccessToken: new sst.Secret("PolarAccessToken"),
	polarSuccessUrl: new sst.Secret("PolarSuccessUrl"),
	polarWebhookSecret: new sst.Secret("PolarWebhookSecret"),
	resendApiKey: new sst.Secret("ResendApiKey"),
	renderOwnerId: new sst.Secret("RenderOwnerId"),
	zeroAdminPassword: new sst.Secret("ZeroAdminPassword"),
	zeroDatabasePassword: new sst.Secret("ZeroDatabasePassword"),
	zeroDatabaseUsername: new sst.Secret("ZeroDatabaseUsername"),
};

export const apiSecrets = [
	secrets.betterAuthSecret,
	secrets.gitHubClientId,
	secrets.gitHubClientSecret,
	secrets.gmailOauthClientId,
	secrets.gmailOauthClientSecret,
	secrets.gmailOauthRedirectUri,
	secrets.gmailPubSubTopic,
	secrets.mailKek,
	secrets.polarAccessToken,
	secrets.polarSuccessUrl,
	secrets.polarWebhookSecret,
	secrets.resendApiKey,
];
