/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as TermsOfServiceRouteImport } from './pages/terms-of-service'
import { Route as SignupRouteImport } from './pages/signup'
import { Route as ResetPasswordRouteImport } from './pages/reset-password'
import { Route as PrivacyPolicyRouteImport } from './pages/privacy-policy'
import { Route as LoginRouteImport } from './pages/login'
import { Route as ForgotPasswordRouteImport } from './pages/forgot-password'
import { Route as CreateOrganizationRouteImport } from './pages/create-organization'
import { Route as AppRouteImport } from './pages/app'
import { Route as SlugRouteImport } from './pages/$organization'
import { Route as IndexRouteImport } from './pages/index'
import { Route as SlugIndexRouteImport } from './pages/$organization.index'
import { Route as SlugSettingsRouteImport } from './pages/$organization.settings'
import { Route as SlugSettingsIndexRouteImport } from './pages/$organization.settings.index'
import { Route as SlugTeamsTeamSlugRouteImport } from './pages/$organization.teams.$team'
import { Route as SlugSettingsTeamsRouteImport } from './pages/$organization.settings.teams'
import { Route as SlugSettingsProfileRouteImport } from './pages/$organization.settings.profile'
import { Route as SlugSettingsPreferencesRouteImport } from './pages/$organization.settings.preferences'
import { Route as SlugSettingsMembersRouteImport } from './pages/$organization.settings.members'
import { Route as SlugSettingsBillingRouteImport } from './pages/$organization.settings.billing'
import { Route as SlugTeamsTeamSlugIndexRouteImport } from './pages/$organization.teams.$team.index'
import { Route as SlugTeamsTeamSlugSettingsRouteImport } from './pages/$organization.teams.$team.settings'
import { Route as SlugTeamsTeamSlugSettingsIndexRouteImport } from './pages/$organization.teams.$team.settings.index'
import { Route as SlugTeamsTeamSlugSettingsMembersRouteImport } from './pages/$organization.teams.$team.settings.members'
import { Route as SlugTeamsTeamSlugSettingsGeneralRouteImport } from './pages/$organization.teams.$team.settings.general'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$organization',
  path: '/$organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SlugSettingsRoute = SlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SlugRoute,
} as any)
const SlugSettingsIndexRoute = SlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugSettingsRoute,
} as any)
const SlugTeamsTeamSlugRoute = SlugTeamsTeamSlugRouteImport.update({
  id: '/teams/$team',
  path: '/teams/$team',
  getParentRoute: () => SlugRoute,
} as any)
const SlugSettingsTeamsRoute = SlugSettingsTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => SlugSettingsRoute,
} as any)
const SlugSettingsProfileRoute = SlugSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SlugSettingsRoute,
} as any)
const SlugSettingsPreferencesRoute = SlugSettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SlugSettingsRoute,
} as any)
const SlugSettingsMembersRoute = SlugSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => SlugSettingsRoute,
} as any)
const SlugSettingsBillingRoute = SlugSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SlugSettingsRoute,
} as any)
const SlugTeamsTeamSlugIndexRoute = SlugTeamsTeamSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugTeamsTeamSlugRoute,
} as any)
const SlugTeamsTeamSlugSettingsRoute =
  SlugTeamsTeamSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => SlugTeamsTeamSlugRoute,
  } as any)
const SlugTeamsTeamSlugSettingsIndexRoute =
  SlugTeamsTeamSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SlugTeamsTeamSlugSettingsRoute,
  } as any)
const SlugTeamsTeamSlugSettingsMembersRoute =
  SlugTeamsTeamSlugSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => SlugTeamsTeamSlugSettingsRoute,
  } as any)
const SlugTeamsTeamSlugSettingsGeneralRoute =
  SlugTeamsTeamSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => SlugTeamsTeamSlugSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$organization': typeof SlugRouteWithChildren
  '/app': typeof AppRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$organization/settings': typeof SlugSettingsRouteWithChildren
  '/$organization/': typeof SlugIndexRoute
  '/$organization/settings/billing': typeof SlugSettingsBillingRoute
  '/$organization/settings/members': typeof SlugSettingsMembersRoute
  '/$organization/settings/preferences': typeof SlugSettingsPreferencesRoute
  '/$organization/settings/profile': typeof SlugSettingsProfileRoute
  '/$organization/settings/teams': typeof SlugSettingsTeamsRoute
  '/$organization/teams/$team': typeof SlugTeamsTeamSlugRouteWithChildren
  '/$organization/settings/': typeof SlugSettingsIndexRoute
  '/$organization/teams/$team/settings': typeof SlugTeamsTeamSlugSettingsRouteWithChildren
  '/$organization/teams/$team/': typeof SlugTeamsTeamSlugIndexRoute
  '/$organization/teams/$team/settings/general': typeof SlugTeamsTeamSlugSettingsGeneralRoute
  '/$organization/teams/$team/settings/members': typeof SlugTeamsTeamSlugSettingsMembersRoute
  '/$organization/teams/$team/settings/': typeof SlugTeamsTeamSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$organization': typeof SlugIndexRoute
  '/$organization/settings/billing': typeof SlugSettingsBillingRoute
  '/$organization/settings/members': typeof SlugSettingsMembersRoute
  '/$organization/settings/preferences': typeof SlugSettingsPreferencesRoute
  '/$organization/settings/profile': typeof SlugSettingsProfileRoute
  '/$organization/settings/teams': typeof SlugSettingsTeamsRoute
  '/$organization/settings': typeof SlugSettingsIndexRoute
  '/$organization/teams/$team': typeof SlugTeamsTeamSlugIndexRoute
  '/$organization/teams/$team/settings/general': typeof SlugTeamsTeamSlugSettingsGeneralRoute
  '/$organization/teams/$team/settings/members': typeof SlugTeamsTeamSlugSettingsMembersRoute
  '/$organization/teams/$team/settings': typeof SlugTeamsTeamSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$organization': typeof SlugRouteWithChildren
  '/app': typeof AppRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$organization/settings': typeof SlugSettingsRouteWithChildren
  '/$organization/': typeof SlugIndexRoute
  '/$organization/settings/billing': typeof SlugSettingsBillingRoute
  '/$organization/settings/members': typeof SlugSettingsMembersRoute
  '/$organization/settings/preferences': typeof SlugSettingsPreferencesRoute
  '/$organization/settings/profile': typeof SlugSettingsProfileRoute
  '/$organization/settings/teams': typeof SlugSettingsTeamsRoute
  '/$organization/teams/$team': typeof SlugTeamsTeamSlugRouteWithChildren
  '/$organization/settings/': typeof SlugSettingsIndexRoute
  '/$organization/teams/$team/settings': typeof SlugTeamsTeamSlugSettingsRouteWithChildren
  '/$organization/teams/$team/': typeof SlugTeamsTeamSlugIndexRoute
  '/$organization/teams/$team/settings/general': typeof SlugTeamsTeamSlugSettingsGeneralRoute
  '/$organization/teams/$team/settings/members': typeof SlugTeamsTeamSlugSettingsMembersRoute
  '/$organization/teams/$team/settings/': typeof SlugTeamsTeamSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organization'
    | '/app'
    | '/create-organization'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms-of-service'
    | '/$organization/settings'
    | '/$organization/'
    | '/$organization/settings/billing'
    | '/$organization/settings/members'
    | '/$organization/settings/preferences'
    | '/$organization/settings/profile'
    | '/$organization/settings/teams'
    | '/$organization/teams/$team'
    | '/$organization/settings/'
    | '/$organization/teams/$team/settings'
    | '/$organization/teams/$team/'
    | '/$organization/teams/$team/settings/general'
    | '/$organization/teams/$team/settings/members'
    | '/$organization/teams/$team/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/create-organization'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms-of-service'
    | '/$organization'
    | '/$organization/settings/billing'
    | '/$organization/settings/members'
    | '/$organization/settings/preferences'
    | '/$organization/settings/profile'
    | '/$organization/settings/teams'
    | '/$organization/settings'
    | '/$organization/teams/$team'
    | '/$organization/teams/$team/settings/general'
    | '/$organization/teams/$team/settings/members'
    | '/$organization/teams/$team/settings'
  id:
    | '__root__'
    | '/'
    | '/$organization'
    | '/app'
    | '/create-organization'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms-of-service'
    | '/$organization/settings'
    | '/$organization/'
    | '/$organization/settings/billing'
    | '/$organization/settings/members'
    | '/$organization/settings/preferences'
    | '/$organization/settings/profile'
    | '/$organization/settings/teams'
    | '/$organization/teams/$team'
    | '/$organization/settings/'
    | '/$organization/teams/$team/settings'
    | '/$organization/teams/$team/'
    | '/$organization/teams/$team/settings/general'
    | '/$organization/teams/$team/settings/members'
    | '/$organization/teams/$team/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AppRoute: typeof AppRoute
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organization': {
      id: '/$organization'
      path: '/$organization'
      fullPath: '/$organization'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organization/': {
      id: '/$organization/'
      path: '/'
      fullPath: '/$organization/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$organization/settings': {
      id: '/$organization/settings'
      path: '/settings'
      fullPath: '/$organization/settings'
      preLoaderRoute: typeof SlugSettingsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$organization/settings/': {
      id: '/$organization/settings/'
      path: '/'
      fullPath: '/$organization/settings/'
      preLoaderRoute: typeof SlugSettingsIndexRouteImport
      parentRoute: typeof SlugSettingsRoute
    }
    '/$organization/teams/$team': {
      id: '/$organization/teams/$team'
      path: '/teams/$team'
      fullPath: '/$organization/teams/$team'
      preLoaderRoute: typeof SlugTeamsTeamSlugRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$organization/settings/teams': {
      id: '/$organization/settings/teams'
      path: '/teams'
      fullPath: '/$organization/settings/teams'
      preLoaderRoute: typeof SlugSettingsTeamsRouteImport
      parentRoute: typeof SlugSettingsRoute
    }
    '/$organization/settings/profile': {
      id: '/$organization/settings/profile'
      path: '/profile'
      fullPath: '/$organization/settings/profile'
      preLoaderRoute: typeof SlugSettingsProfileRouteImport
      parentRoute: typeof SlugSettingsRoute
    }
    '/$organization/settings/preferences': {
      id: '/$organization/settings/preferences'
      path: '/preferences'
      fullPath: '/$organization/settings/preferences'
      preLoaderRoute: typeof SlugSettingsPreferencesRouteImport
      parentRoute: typeof SlugSettingsRoute
    }
    '/$organization/settings/members': {
      id: '/$organization/settings/members'
      path: '/members'
      fullPath: '/$organization/settings/members'
      preLoaderRoute: typeof SlugSettingsMembersRouteImport
      parentRoute: typeof SlugSettingsRoute
    }
    '/$organization/settings/billing': {
      id: '/$organization/settings/billing'
      path: '/billing'
      fullPath: '/$organization/settings/billing'
      preLoaderRoute: typeof SlugSettingsBillingRouteImport
      parentRoute: typeof SlugSettingsRoute
    }
    '/$organization/teams/$team/': {
      id: '/$organization/teams/$team/'
      path: '/'
      fullPath: '/$organization/teams/$team/'
      preLoaderRoute: typeof SlugTeamsTeamSlugIndexRouteImport
      parentRoute: typeof SlugTeamsTeamSlugRoute
    }
    '/$organization/teams/$team/settings': {
      id: '/$organization/teams/$team/settings'
      path: '/settings'
      fullPath: '/$organization/teams/$team/settings'
      preLoaderRoute: typeof SlugTeamsTeamSlugSettingsRouteImport
      parentRoute: typeof SlugTeamsTeamSlugRoute
    }
    '/$organization/teams/$team/settings/': {
      id: '/$organization/teams/$team/settings/'
      path: '/'
      fullPath: '/$organization/teams/$team/settings/'
      preLoaderRoute: typeof SlugTeamsTeamSlugSettingsIndexRouteImport
      parentRoute: typeof SlugTeamsTeamSlugSettingsRoute
    }
    '/$organization/teams/$team/settings/members': {
      id: '/$organization/teams/$team/settings/members'
      path: '/members'
      fullPath: '/$organization/teams/$team/settings/members'
      preLoaderRoute: typeof SlugTeamsTeamSlugSettingsMembersRouteImport
      parentRoute: typeof SlugTeamsTeamSlugSettingsRoute
    }
    '/$organization/teams/$team/settings/general': {
      id: '/$organization/teams/$team/settings/general'
      path: '/general'
      fullPath: '/$organization/teams/$team/settings/general'
      preLoaderRoute: typeof SlugTeamsTeamSlugSettingsGeneralRouteImport
      parentRoute: typeof SlugTeamsTeamSlugSettingsRoute
    }
  }
}

interface SlugSettingsRouteChildren {
  SlugSettingsBillingRoute: typeof SlugSettingsBillingRoute
  SlugSettingsMembersRoute: typeof SlugSettingsMembersRoute
  SlugSettingsPreferencesRoute: typeof SlugSettingsPreferencesRoute
  SlugSettingsProfileRoute: typeof SlugSettingsProfileRoute
  SlugSettingsTeamsRoute: typeof SlugSettingsTeamsRoute
  SlugSettingsIndexRoute: typeof SlugSettingsIndexRoute
}

const SlugSettingsRouteChildren: SlugSettingsRouteChildren = {
  SlugSettingsBillingRoute: SlugSettingsBillingRoute,
  SlugSettingsMembersRoute: SlugSettingsMembersRoute,
  SlugSettingsPreferencesRoute: SlugSettingsPreferencesRoute,
  SlugSettingsProfileRoute: SlugSettingsProfileRoute,
  SlugSettingsTeamsRoute: SlugSettingsTeamsRoute,
  SlugSettingsIndexRoute: SlugSettingsIndexRoute,
}

const SlugSettingsRouteWithChildren = SlugSettingsRoute._addFileChildren(
  SlugSettingsRouteChildren,
)

interface SlugTeamsTeamSlugSettingsRouteChildren {
  SlugTeamsTeamSlugSettingsGeneralRoute: typeof SlugTeamsTeamSlugSettingsGeneralRoute
  SlugTeamsTeamSlugSettingsMembersRoute: typeof SlugTeamsTeamSlugSettingsMembersRoute
  SlugTeamsTeamSlugSettingsIndexRoute: typeof SlugTeamsTeamSlugSettingsIndexRoute
}

const SlugTeamsTeamSlugSettingsRouteChildren: SlugTeamsTeamSlugSettingsRouteChildren =
  {
    SlugTeamsTeamSlugSettingsGeneralRoute:
      SlugTeamsTeamSlugSettingsGeneralRoute,
    SlugTeamsTeamSlugSettingsMembersRoute:
      SlugTeamsTeamSlugSettingsMembersRoute,
    SlugTeamsTeamSlugSettingsIndexRoute: SlugTeamsTeamSlugSettingsIndexRoute,
  }

const SlugTeamsTeamSlugSettingsRouteWithChildren =
  SlugTeamsTeamSlugSettingsRoute._addFileChildren(
    SlugTeamsTeamSlugSettingsRouteChildren,
  )

interface SlugTeamsTeamSlugRouteChildren {
  SlugTeamsTeamSlugSettingsRoute: typeof SlugTeamsTeamSlugSettingsRouteWithChildren
  SlugTeamsTeamSlugIndexRoute: typeof SlugTeamsTeamSlugIndexRoute
}

const SlugTeamsTeamSlugRouteChildren: SlugTeamsTeamSlugRouteChildren = {
  SlugTeamsTeamSlugSettingsRoute: SlugTeamsTeamSlugSettingsRouteWithChildren,
  SlugTeamsTeamSlugIndexRoute: SlugTeamsTeamSlugIndexRoute,
}

const SlugTeamsTeamSlugRouteWithChildren =
  SlugTeamsTeamSlugRoute._addFileChildren(SlugTeamsTeamSlugRouteChildren)

interface SlugRouteChildren {
  SlugSettingsRoute: typeof SlugSettingsRouteWithChildren
  SlugIndexRoute: typeof SlugIndexRoute
  SlugTeamsTeamSlugRoute: typeof SlugTeamsTeamSlugRouteWithChildren
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugSettingsRoute: SlugSettingsRouteWithChildren,
  SlugIndexRoute: SlugIndexRoute,
  SlugTeamsTeamSlugRoute: SlugTeamsTeamSlugRouteWithChildren,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AppRoute: AppRoute,
  CreateOrganizationRoute: CreateOrganizationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
